version: '3.8'

services:
  # Override for development environment
  notification-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Logging__LogLevel__Default=Debug
      - Logging__Elasticsearch__Enabled=true
    volumes:
      - ./src/NotificationService.Api:/app/src:ro
      - api_logs:/app/logs
    ports:
      - "8080:8080"
      - "8081:8081"

  notification-worker:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Debug
      - Logging__Elasticsearch__Enabled=true
    volumes:
      - ./src/NotificationService.Worker:/app/src:ro
      - worker_logs:/app/logs

  # Development tools
  mongodb-express:
    image: mongo-express:1.0.0-alpha
    container_name: notification-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8082:8081"
    depends_on:
      - mongodb
    networks:
      - notification-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: notification-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379:0:redis123
    ports:
      - "8083:8081"
    depends_on:
      - redis
    networks:
      - notification-network