apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "notification-service-logs-*"
    basicAuth: false
    isDefault: false
    jsonData:
      esVersion: "8.11.0"
      timeField: "@timestamp"
      logMessageField: "message"
      logLevelField: "level"